### ISSUE TITLE
Worker warning messages: DEADLINE_EXCEEDED: deadline exceeded after 69.999

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1046]
1. Set sslContext on WorkflowServiceStubs

             WorkflowServiceStubs.newInstance(
                    WorkflowServiceStubsOptions.newBuilder()
                            .setSslContext(SimpleSslContextBuilder.forPKCS8(CLIENT_CERT, CLIENT_KEY).build())
                            .setTarget(TARGET_ENDPOINT)
                            .build());

2. Create client and workflowFactory, create worker and start factory

3. Let the worker run for some time, no need to run workflows

Getting following two warnings about every 1 minute with no workflows running:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Subchannel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.pollActivityTaskQueue(WorkflowServiceGrpc.java:2702)
	at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:99)
	at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:39)
	at io.temporal.internal.worker.Poller$PollExecutionTask.run(Poller.java:262)
	at io.temporal.internal.worker.Poller$PollLoopTask.run(Poller.java:227)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

and 

```
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 69.999671598s. [closed=[], open=[[remote_addr=tihomir.temporal-dev.tmprl.cloud/34.228.207.69:7233]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.pollActivityTaskQueue(WorkflowServiceGrpc.java:2702)
	at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:99)
	at io.temporal.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:39)
	at io.temporal.internal.worker.Poller$PollExecutionTask.run(Poller.java:262)
	at io.temporal.internal.worker.Poller$PollLoopTask.run(Poller.java:227)
```

Worker still picks up workflow tasks, and you can run your workflows. Just these warnings keep popping up when worker is running but idle. 
Used sdk verion 1.7.1 (cant test on 1.8.0 yet because of the maven issue, will test on 1.9.0)

Similar issue that was resolved: https://github.com/temporalio/sdk-java/issues/707
This is not related to test env (not using it)

**Comment by josh-berry** [comment]
@tsurdilo Have you seen this one recently? Wondering if it's still an issue or if it can just be closed.
