### ISSUE TITLE
INVALID_ARGUMENT thrown when trying to complete an activity thats already completed

### ISSUE THREAD

**Issue by darewreck54** [temporalio/sdk-java#1055]
The exception below is thrown when trying to complete an activity.  

based on this thread https://community.temporal.io/t/reasonable-values-for-task-pollers/2257/2?u=darewreck it states that this could be due to 

```
due to activity timeouts. When an activity takes longer to complete than its StartToClose timeout the call to the service with the activity result is rejected with this message.
```

In my case, the argument gets thrown because the activity is already completed.   Shouldn't another exception be thrown vs. `INVALID_ARGUMENT`

```
"io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Cannot locate Activity ScheduleID
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompletedById(WorkflowServiceGrpc.java:2762)
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.complete(ManualActivityCompletionClientImpl.java:135)
	... 85 common frames omitted
Wrapped by: io.temporal.client.ActivityCompletionFailureException: ActivityId=2be5aea6-d792-3e8d-b0ee-9117f6b246a8
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.processException(ManualActivityCompletionClientImpl.java:294)
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.complete(ManualActivityCompletionClientImpl.java:137)
	at io.temporal.internal.sync.ActivityCompletionClientImpl.complete(ActivityCompletionClientImpl.java:53)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:80)
	at com.sun.proxy.$Proxy112.complete(Unknown Source)
```

**Comment by Spikhalskiy** [comment]
This is not a JavaSDK issue, this response code is defined by the server - transferring the issue into temporal/temporal repo.
