### ISSUE TITLE
Intermittent testWorkflowMetrics Unit test failure

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#107]
## Expected Behavior
Test always passing

## Actual Behavior
When running in a constrained CI/CD environment it sometimes fails:

```
io.temporal.workflow.MetricsTest > testWorkflowMetrics FAILED
    java.lang.AssertionError: 3.39s
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at io.temporal.workflow.MetricsTest.testWorkflowMetrics(MetricsTest.java:280)
```

**Comment by vitarb** [comment]
Possibly fixed, need to double check.
