### ISSUE TITLE
Workflow metadata resolution code registers an overridden method from parent class as a second query

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1107]
## Expected Behavior

Such a workflow interfaces hierarchy:

```
@WorkflowInterface
public interface ReportingWorkflow extends TemporalWorkflow<ReportQueriesResponse> {
  @WorkflowMethod
  ReportQueriesResponse runReport(ReportQueries reportQueries);

  @QueryMethod
  @Override
  ReportQueriesResponse getResults();
}

public interface TemporalWorkflow<T> extends TemporalRunnable {
  T getResults();
}
```

should be fine.

## Actual Behavior

Triggers `java.lang.IllegalArgumentException: Duplicated name of QUERY: "getResults" declared at "public abstract xxx.ReportingProto$ReportQueriesResponse xxx.ReportingWorkflow.getResults()" and "public default java.lang.Object xxx.ReportingWorkflow.getResults()"`

## Specifications

  - Version: 1.8.x

**Comment by shabalin** [comment]
The same happened if you override with @WorkflowMethod
```
public interface TemporalWorkflow<T> {
    void execute(T params);
}
```
and then define the actual workflow interface:
```
@WorkflowInterface
public interface SearchTaskWorkflow extends TemporalWorkflow<SearchWorkflowParams> {
    @WorkflowMethod
    @Override
    void execute(SearchWorkflowParams params);
}
```
Workflow registration fails with the error:
```
java.lang.IllegalArgumentException: Duplicated @WorkflowMethod: public default void io.dev.analytics.temporal.SearchTaskWorkflow.execute(java.lang.Object) and public abstract void io.dev.analytics.temporal.SearchTaskWorkflow.execute(io.dev.analytics.service.search.async.SearchWorkflowParams)
	at io.temporal.common.metadata.POJOWorkflowInterfaceMetadata.getWorkflowInterfaceMethods(POJOWorkflowInterfaceMetadata.java:296) ~[temporal-sdk-1.16.0.jar:na]
	at io.temporal.common.metadata.POJOWorkflowInterfaceMetadata.<init>(POJOWorkflowInterfaceMetadata.java:205) ~[temporal-sdk-1.16.0.jar:na]
	at io.temporal.common.metadata.POJOWorkflowInterfaceMetadata.newInstanceInternal(POJOWorkflowInterfaceMetadata.java:184) ~[temporal-sdk-1.16.0.jar:na]
	at io.temporal.common.metadata.POJOWorkflowInterfaceMetadata.newImplementationInstance(POJOWorkflowInterfaceMetadata.java:153) ~[temporal-sdk-1.16.0.jar:na]
	at io.temporal.common.metadata.POJOWorkflowImplMetadata.<init>(POJOWorkflowImplMetadata.java:107) ~[temporal-sdk-1.16.0.jar:na]
	at io.temporal.common.metadata.POJOWorkflowImplMetadata.newInstance(POJOWorkflowImplMetadata.java:75) ~[temporal-sdk-1.16.0.jar:na]
```

In documentation it's said 
> Note that this approach does not apply to @WorkflowMethod annotations, meaning that when using a base interface, it should not include any @WorkflowMethod methods

but we don't mark the parent interface method with a @WorkflowMethod


I think the reason it's happening is in:
`POJOWorkflowInterfaceMetadata.getWorkflowInterfaceMethods`

```
    Method[] declaredMethods = current.getDeclaredMethods();
    for (Method declaredMethod : declaredMethods) {
      POJOWorkflowMethod methodMetadata = new POJOWorkflowMethod(declaredMethod);
      if (validateAndQualifiedForWorkflowMethod(methodMetadata)) {
        result.add(methodMetadata);
      }
    }

```

the  `current.getDeclaredMethods()` returns both methods and then in POJOWorkflowMethod constructor there is this
```
 WorkflowMethod workflowMethod = method.getAnnotation(WorkflowMethod.class);
```
which return not null result for both methods and that causes an error
