### ISSUE TITLE
Latest test-server is broken

### ISSUE THREAD

**Issue by loopingrage** [temporalio/sdk-java#1357]
## Expected Behavior
A working test server

## Actual Behavior
A busted test-server

## Steps to Reproduce the Problem

  1. Run the temporal typescript test server test [here](https://github.com/temporalio/samples-typescript/blob/main/activities-examples/src/workflows.test.ts)

## Specifications

  - Version: Temporal Typescript SDK 1.0.1
  - Platform: Mac

## Details
The temporal Typescript SDK [simply pulls](https://github.com/temporalio/sdk-typescript/blob/main/packages/testing/scripts/download-test-server.mjs) the latest build of test server which currently fails with a bunch of Java NoCLassDefFound errors.

```
Exception in thread "grpc-default-executor-3" java.lang.ExceptionInInitializerError
        at io.temporal.api.common.v1.Payload$MetadataDefaultEntryHolder.<clinit>(Payload.java:124)
        at io.temporal.api.common.v1.Payload.<init>(Payload.java:61)
        at io.temporal.api.common.v1.Payload.<init>(Payload.java:15)
        at io.temporal.api.common.v1.Payload$1.parsePartialFrom(Payload.java:754)
        at io.temporal.api.common.v1.Payload$1.parsePartialFrom(Payload.java:748)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at io.temporal.api.common.v1.Payloads.<init>(Payloads.java:63)
        at io.temporal.api.common.v1.Payloads.<init>(Payloads.java:13)
        at io.temporal.api.common.v1.Payloads$1.parsePartialFrom(Payloads.java:754)
        at io.temporal.api.common.v1.Payloads$1.parsePartialFrom(Payloads.java:748)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest.<init>(StartWorkflowExecutionRequest.java:100)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest.<init>(StartWorkflowExecutionRequest.java:9)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest$1.parsePartialFrom(StartWorkflowExecutionRequest.java:3376)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest$1.parsePartialFrom(StartWorkflowExecutionRequest.java:3370)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
        at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:307)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.RuntimeException: Generated message class "com.google.protobuf.DescriptorProtos$FieldOptions" missing method "getUnverifiedLazy".
        at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
        at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2178)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2252)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1982)
        at com.google.protobuf.DescriptorProtos$FieldOptions.internalGetFieldAccessorTable(DescriptorProtos.java:28933)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
        at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.parseUnknownField(GeneratedMessageV3.java:1134)
        at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:28901)
        at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:28795)
        at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:31031)
        at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:31025)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11706)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11598)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:14351)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:14345)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5232)
        at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5168)
        at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:10305)
        at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:10299)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1283)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1203)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4892)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4886)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:2301)
        at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:417)
        at io.temporal.api.common.v1.MessageProto.<clinit>(MessageProto.java:134)
        ... 31 more
Caused by: java.lang.NoSuchMethodException: com.google.protobuf.DescriptorProtos$FieldOptions.getUnverifiedLazy()
        at java.lang.Class.getMethod(DynamicHub.java:2227)
        at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
        ... 65 more
Exception in thread "grpc-default-executor-3" java.lang.ExceptionInInitializerError
        at io.temporal.api.common.v1.Payload$MetadataDefaultEntryHolder.<clinit>(Payload.java:124)
        at io.temporal.api.common.v1.Payload.<init>(Payload.java:61)
        at io.temporal.api.common.v1.Payload.<init>(Payload.java:15)
        at io.temporal.api.common.v1.Payload$1.parsePartialFrom(Payload.java:754)
        at io.temporal.api.common.v1.Payload$1.parsePartialFrom(Payload.java:748)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at io.temporal.api.common.v1.Payloads.<init>(Payloads.java:63)
        at io.temporal.api.common.v1.Payloads.<init>(Payloads.java:13)
        at io.temporal.api.common.v1.Payloads$1.parsePartialFrom(Payloads.java:754)
        at io.temporal.api.common.v1.Payloads$1.parsePartialFrom(Payloads.java:748)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest.<init>(StartWorkflowExecutionRequest.java:100)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest.<init>(StartWorkflowExecutionRequest.java:9)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest$1.parsePartialFrom(StartWorkflowExecutionRequest.java:3376)
        at io.temporal.api.workflowservice.v1.StartWorkflowExecutionRequest$1.parsePartialFrom(StartWorkflowExecutionRequest.java:3370)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
        at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:307)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.RuntimeException: Generated message class "com.google.protobuf.DescriptorProtos$FieldOptions" missing method "getUnverifiedLazy".
        at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
        at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2178)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2252)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1982)
        at com.google.protobuf.DescriptorProtos$FieldOptions.internalGetFieldAccessorTable(DescriptorProtos.java:28933)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
        at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.parseUnknownField(GeneratedMessageV3.java:1134)
        at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:28901)
        at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:28795)
        at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:31031)
        at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:31025)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11706)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11598)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:14351)
        at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:14345)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
        at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5232)
        at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5168)
        at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom...
```

**Comment by Spikhalskiy** [comment]
We mitigated the problem. You should be able to use the TS testing framework back.
