### ISSUE TITLE
Multiple tests launched from test class with mocked activity method fail, but each when launch separately passes

### ISSUE THREAD

**Issue by idkomarov** [temporalio/sdk-java#1518]
## Description
I am trying to test my Temporal Workflow using temporal java-sdk, temporal-testing, JUnit and Mockito. This workflow has single workflow method including single activity method execution. As activity method uses external service, in unit test I use its mock. I've written multiple tests which check multiple workflow behaviors. Each test passes when launches separately, but if I run whole test class only first test passes and all next tests fail: **my mocking declarations in** `when` **construction don't work in failed tests, workflows fall because they couldn't connect to external service**. Tried to launch tests using different constructions and different Temporal sdk version but have the same behavior.

## Expected Behavior
All tests pass when they launch together.

## Actual Behavior
Only first test passes and all other fail when they launch together.

## Steps to Reproduce the Problem
1. Write Workflow & Activity according to description above
2. Run test like this (`ActivityInterface` - `ExternalServiceHelper`, `WorflowInterface` - `SomeFeatureDeactivator`)
```
@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class SomeFeatureDeactivatorImplTest {

    private TestWorkflowEnvironment testEnv;
    private Worker worker;
    private WorkflowClient client;

    private static final String ID = "123";

    @MockBean
    ExternalServiceHelperImpl externalServiceHelper;

    @BeforeEach
    public void setUp() {
        testEnv = TestWorkflowEnvironment.newInstance();
        worker = testEnv.newWorker(QUEUE);
        worker.registerWorkflowImplementationTypes(SomeFeatureDeactivatorImpl.class);
        worker.registerActivitiesImplementations(externalServiceHelper);
        client = testEnv.getWorkflowClient();
        testEnv.start();
    }

    @AfterEach
    public void tearDown() {
        testEnv.close();
    }

    @Test
    @Timeout(10)
    @Order(0)
    void processEntityWithIdTest_givenIdIsNull() {
        // given, when
        WorkflowOptions workflowOptions = WorkflowOptions.newBuilder()
                .setTaskQueue(QUEUE)
                .build();
        SomeFeatureDeactivator someFeatureDeactivator =
                client.newWorkflowStub(SomeFeatureDeactivator.class, workflowOptions);

        someFeatureDeactivator.processEntityWithId(null);

        // then
        verify(externalServiceHelper, never()).sendMessageToDeactivateFeature(null);
    }

    @Test
    @Timeout(10)
    @Order(1)
    void processEntityWithIdTest() {
        // given
        doNothing().when(externalServiceHelper).sendMessageToDeactivateFeature(anyString());

        // when
        WorkflowOptions workflowOptions = WorkflowOptions.newBuilder()
                .setTaskQueue(QUEUE)
                .build();
        SomeFeatureDeactivator someFeatureDeactivator =
                client.newWorkflowStub(SomeFeatureDeactivator.class, workflowOptions);

        someFeatureDeactivator.processEntityWithId(ID);

        // then
        verify(externalServiceHelper, only()).sendMessageToDeactivateFeature(ID);
    }

    @Test
    @Timeout(10)
    @Order(2)
    void processEntityWithIdTest_retrySendToMessageToExternalService() {
        // given
        doThrow(new RuntimeException())
                .doThrow(new RuntimeException())
                .doThrow(new RuntimeException())
                .doNothing()
                .when(externalServiceHelper).sendMessageToDeactivateFeature(anyString());

        // when
        WorkflowOptions workflowOptions = WorkflowOptions.newBuilder()
                .setTaskQueue(QUEUE)
                .build();
        SomeFeatureDeactivator someFeatureDeactivator =
                client.newWorkflowStub(SomeFeatureDeactivator.class, workflowOptions);

        someFeatureDeactivator.processEntityWithId(ID);

        // then
        verify(externalServiceHelper, times(4)).sendMessageToDeactivateFeature(ID);
    }
}

```
3. Get tests with order numbers 1 and 2 failed because `%test_name% timed out after 10 seconds`

Got his log on failed `processEntityWithIdTest`
```
2022-11-16 15:28:18.165  INFO 11416 --- [    Test worker] io.temporal.internal.worker.Poller       : start: Poller{name=Workflow Poller taskQueue="UPDATE_DP_ATTRS_QUEUE;", namespace="default", identity=MY-PC-NAME}
2022-11-16 15:28:18.165  INFO 11416 --- [    Test worker] io.temporal.internal.worker.Poller       : start: Poller{name=Local Activity Poller taskQueue="UPDATE_DP_ATTRS_QUEUE;", namespace="default", identity=MY-PC-NAME}
2022-11-16 15:28:18.166  INFO 11416 --- [    Test worker] io.temporal.internal.worker.Poller       : start: Poller{name=Activity Poller taskQueue="UPDATE_DP_ATTRS_QUEUE;", namespace="default", identity=MY-PC-NAME}
2022-11-16 15:28:18.169  INFO 11416 --- [    Test worker] io.temporal.internal.worker.Poller       : start: Poller{name=Sticky Workflow Poller taskQueue="MY-PC-NAME:91c759e5-3a72-41da-b740-6a1208cdc07b", namespace="default", identity=MY-PC-NAME}
2022-11-16 15:28:18.239  WARN 11416 --- [ce="default": 1] i.t.i.replay.ReplayWorkflowTaskHandler   : Workflow task processing failure. startedEventId=3, WorkflowId=160396d9-ad8d-4cab-9f69-c770278e6a7a, RunId=92e9b27d-72d4-470b-b74c-fdc4c4d87991. If seen continuously the workflow might be stuck.

io.temporal.internal.statemachines.InternalWorkflowTaskException: Failure handling event 3 of type 'EVENT_TYPE_WORKFLOW_TASK_STARTED' during execution. {PreviousStartedEventId=0, WorkflowTaskStartedEventId=3, CurrentStartedEventId=3}
	at io.temporal.internal.statemachines.WorkflowStateMachines.createEventProcessingException(WorkflowStateMachines.java:263) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:242) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:216) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:190) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:137) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:129) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:98) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:293) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:237) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:178) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.14.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.RuntimeException: WorkflowTask: failure executing SCHEDULED->WORKFLOW_TASK_STARTED, transition history is [CREATED->WORKFLOW_TASK_SCHEDULED]
	at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:152) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.StateMachine.handleHistoryEvent(StateMachine.java:102) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.EntityStateMachineBase.handleEvent(EntityStateMachineBase.java:68) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleSingleEvent(WorkflowStateMachines.java:276) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventsBatch(WorkflowStateMachines.java:240) ~[temporal-sdk-1.14.0.jar:na]
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: Operation allowed only while eventLoop is running
	at io.temporal.internal.statemachines.WorkflowStateMachines.checkEventLoopExecuting(WorkflowStateMachines.java:1061) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.statemachines.WorkflowStateMachines.randomUUID(WorkflowStateMachines.java:717) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.replay.ReplayWorkflowContextImpl.scheduleActivityTask(ReplayWorkflowContextImpl.java:212) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.SyncWorkflowContext.executeActivityOnce(SyncWorkflowContext.java:251) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.SyncWorkflowContext.executeActivity(SyncWorkflowContext.java:236) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.ActivityStubImpl.executeAsync(ActivityStubImpl.java:50) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:39) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:78) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:71) ~[temporal-sdk-1.14.0.jar:na]
	at com.sun.proxy.$Proxy173.sendMessageToDeactivateFeature(Unknown Source) ~[na:na]
	at my.service.SomeFeatureDeactivatorImpl.processEntityWithId(SomeFeatureDeactivatorImpl.java:26) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:310) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:285) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:68) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107) ~[temporal-sdk-1.14.0.jar:na]
	at io.temporal.worker.WorkerFactory.lambda$newWorkflowThreadExecutor$7(WorkerFactory.java:392) ~[temporal-sdk-1.14.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	... 3 common frames omitted
```

## Additional attempts
I tried to launch tests in various ways: using tutorials from documentation & java-samples
This variant
```
@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class SomeFeatureDeactivatorImplTest {

    @MockBean
    ExternalServiceHelperImpl externalServiceHelper;

    @RegisterExtension
    public static final TestWorkflowExtension testWorkflowExtension =
        TestWorkflowExtension.newBuilder()
                .setWorkflowTypes(SomeFeatureDeactivatorImpl.class)
                .setDoNotStart(true)
                .build();

    @Test
    @Timeout(10)
    @Order(0)
    void processEntityWithIdTest_givenIdIsNull(TestWorkflowEnvironment testEnv, Worker worker, SomeFeatureDeactivator someFeatureDeactivator) {
        worker.registerActivitiesImplementations(externalServiceHelper);
        testEnv.start();

        // given, when
        someFeatureDeactivator.processEntityWithId(null);

        // then
        verify(externalServiceHelper, never()).sendMessageToDeactivateFeature(null);
    }
    ... // same way for other tests
```
and this
```
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class SomeFeatureDeactivatorImplTest {

    @BeforeEach
    public void setUp() {
        testEnv = TestWorkflowEnvironment.newInstance();
        worker = testEnv.newWorker(QUEUE);
        worker.registerWorkflowImplementationTypes(SomeFeatureDeactivatorImpl.class);
        client = testEnv.getWorkflowClient();
    }

    @AfterEach
    public void tearDown() {
        testEnv.close();
    }

    @Test
    @Timeout(10)
    @Order(0)
    void processEntityWithIdTest_givenIdIsNull() {
        // given, when
        ExternalServiceHelper externalServiceHelper = mock(ExternalServiceHelper.class, withSettings().withoutAnnotations());
        worker.registerActivitiesImplementations(externalServiceHelper);
        testEnv.start();

        WorkflowOptions workflowOptions = WorkflowOptions.newBuilder()
                .setTaskQueue(QUEUE)
                .build();
        SomeFeatureDeactivator someFeatureDeactivator =
                client.newWorkflowStub(SomeFeatureDeactivator.class, workflowOptions);

        someFeatureDeactivator.processEntityWithId(null);

        // then
        verify(externalServiceHelper, never()).sendMessageToDeactivateFeature(null);
    }
    ... // same way for other tests
```
don't work too
## Specifications

  - Version: 1.14 or 1.17
  - Platform: Java

**Comment by Spikhalskiy** [comment]
Please provide a full reproduction that can be launched locally.

> Write Workflow & Activity according to description above
This is not enough information.

But I'm pretty sure that ActivityStubs are shared between workflow instances, which is not allowed.

**Comment by idkomarov** [comment]
> Please provide a full reproduction that can be launched locally.

Hello again. I'm back with a reproduction that can be run locally along with tests above. All classes stored as separate files as `public` modificator hints :)
```
@ActivityInterface
public interface ExternalServiceHelper {
    void sendMessageToDeactivateFeature(String id);
}

@Component
public class ExternalServiceHelperImpl implements ExternalServiceHelper {
    private final Random random = new Random();

    @Override
    public void sendMessageToDeactivateFeature(String id) {
        // this is actually a kafka producer invokation
        if (random.nextDouble() <= 0.5D) {
            throw new RuntimeException();
        }
    }
}

@WorkflowInterface
public interface SomeFeatureDeactivator {
    @WorkflowMethod
    void processEntityWithId(String id);
}

public class SomeFeatureDeactivatorImpl implements SomeFeatureDeactivator {
    public static final RetryOptions DEFAULT_RETRY_OPTIONS = RetryOptions.newBuilder()
            .setInitialInterval(Duration.ofSeconds(1))
            .setMaximumInterval(Duration.ofSeconds(10))
            .setBackoffCoefficient(2)
            .setMaximumAttempts(100)
            .build();

    public static final ActivityOptions DEFAULT_ACTIVITY_OPTIONS = ActivityOptions.newBuilder()
            .setStartToCloseTimeout(Duration.ofSeconds(5))
            .setRetryOptions(DEFAULT_RETRY_OPTIONS)
            .build();

    private static final ExternalServiceHelper externalServiceHelper =
            Workflow.newActivityStub(ExternalServiceHelper.class, DEFAULT_ACTIVITY_OPTIONS);

    @Override
    public void processEntityWithId(String id) {
        if (Objects.isNull(id)) {
            return;
        }

        // this is actually some preparations

        externalServiceHelper.sendMessageToDeactivateFeature(id);
    }
}
```
