### ISSUE TITLE
Activity stub throws IllegalArgumentException from toString method

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#1536]
## Expected Behavior
Activity stub returns string information about its configuration and state.

## Actual Behavior
IllegalArgumentException is thrown.

```
Caused by: java.lang.IllegalArgumentException: Unknown method: public java.lang.String java.lang.Object.toString()
	at io.temporal.common.metadata.POJOActivityInterfaceMetadata.getMethodMetadata(POJOActivityInterfaceMetadata.java:124)
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:56)
	at com.sun.proxy.$Proxy46.toString(Unknown Source)
	at io.temporal.samples.moneytransfer.AccountTransferWorkflowImpl.transfer(AccountTransferWorkflowImpl.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:302)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:277)
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:71)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:116)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:106)
	at io.temporal.worker.ActiveThreadReportingExecutor.lambda$submit$0(ActiveThreadReportingExecutor.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted
```

## Steps to Reproduce the Problem

  1. Call toString on any activity stub.

**Comment by Spikhalskiy** [comment]
The same is true for Workflow stubs also

**Comment by jessicalostinspace** [comment]
Following this thread as I'm also running into this issue. My activity is only returning: 
    `return enum1 != null && enum2 != null && enum1 != enum2;` which doesn't _explicitly_ call toString().

**Comment by Quinn-With-Two-Ns** [comment]
@jessicalostinspace can you share the exception and stack trace of the error you go?
