### ISSUE TITLE
[Test server] ConcurrentModificationException on Workflow.upsertSearchAttributesForExecution in tests

### ISSUE THREAD

**Issue by sfc-gh-pjagielski** [temporalio/sdk-java#1802]
## Expected Behavior
`Workflow.upsertTypedSearchAttributes` calls are successful in tests

## Actual Behavior
```
    Caused by: java.util.ConcurrentModificationException: null
    	at java.base/java.util.HashMap.compute(HashMap.java:1317)
    	at io.temporal.internal.testservice.TestVisibilityStoreImpl.upsertSearchAttributesForExecution(TestVisibilityStoreImpl.java:97)
    	at io.temporal.internal.testservice.TestWorkflowMutableStateImpl.processUpsertWorkflowSearchAttributes(TestWorkflowMutableStateImpl.java:1542)
    	at io.temporal.internal.testservice.TestWorkflowMutableStateImpl.processCommand(TestWorkflowMutableStateImpl.java:686)
    	at io.temporal.internal.testservice.TestWorkflowMutableStateImpl.lambda$completeWorkflowTask$4(TestWorkflowMutableStateImpl.java:488)
    	at io.temporal.internal.testservice.TestWorkflowMutableStateImpl.update(TestWorkflowMutableStateImpl.java:317)
    	... 12 common frames omitted
```

## Steps to Reproduce the Problem

See https://github.com/sfc-gh-pjagielski/temporal-playground/blob/main/src/main/kotlin/com/snowflake/HelloWorkflow.kt#L37
Failing build: https://github.com/sfc-gh-pjagielski/temporal-playground/actions/runs/5412424059/jobs/9836504936#step:5:837

## Specifications

  - Version: 1.20

**Comment by cretz** [comment]
Thanks for the report. Note, the time-skipping test server (and therefore TestWorkflowExtension using default built-in test server) is not built to run multiple top-level workflows concurrently. Time skipping is applied globally. So if one workflow is waiting on an activity (which disables time-skipping so it runs in real time) but another workflow is expected to time-skip until timeout, the latter won't happen immediately.

@Quinn-With-Two-Ns and/or @mjameswh - while our test service isn't really built for concurrent top-level workflows, the map at https://github.com/temporalio/sdk-java/blob/57cb086f7df02c54e6952f46855eb9118c4b77ca/temporal-test-server/src/main/java/io/temporal/internal/testservice/TestVisibilityStoreImpl.java#L58 should be concurrent map because technically child workflows can run concurrently too. I guess this was just missed in #1067. It seems other non-thread-safe constructs are used in `TestWorkflowMutableStateImpl` but that is per workflow execution so none of that code will run concurrently, and `TestWorkflowStoreImpl` locks things it uses, so it's just this field in `TestVisibilityStoreImpl` we need to fix.

**Comment by sfc-gh-pjagielski** [comment]
@cretz thanks for the analysis! 
Currently we have some tests with concurrent workflows and this is the only issue that we're facing. Commenting out the code with `upsertSearchAttributes` helps, so I guess the change to `ConcurrentHashMap` should help
