### ISSUE TITLE
Spring Boot 3 native image support

### ISSUE THREAD

**Issue by zhxnlai** [temporalio/sdk-java#1840]
**Is your feature request related to a problem? Please describe.**

During native image build, Spring Boot auto-configuration fails with the following error message:
```
[           main] ocalVariableTableParameterNameDiscoverer : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: io.temporal.spring.boot.autoconfigure.properties.WorkerProperties
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
	io.temporal.spring.boot.autoconfigure.properties.WorkerProperties
	io.temporal.spring.boot.autoconfigure.properties.WorkerProperties$CapacityConfigurationProperties
	io.temporal.spring.boot.autoconfigure.properties.TemporalProperties
	io.temporal.spring.boot.autoconfigure.properties.WorkerProperties$RateLimitsConfigurationProperties
	io.temporal.spring.boot.autoconfigure.properties.NamespaceProperties$WorkflowCacheProperties

	at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:100)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:74)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processAot'.
```

**Describe the solution you'd like**
Add the following to `temporal-spring-boot-autoconfigure-alpha/build.gradle`
```
// build.gradle
tasks.withType<JavaCompile> { options.compilerArgs = options.compilerArgs + "-parameters" }
```

**Comment by Quinn-With-Two-Ns** [comment]
closed by https://github.com/temporalio/sdk-java/pull/1877
