### ISSUE TITLE
Netty NioEventLoop exception

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#192]
## Expected Behavior
gRPC works.

## Actual Behavior
Intermittently unit tests get blocked producing a bunch of exceptions into the log:
```
19:26:22.214 [grpc-nio-worker-ELG-1-14] WARN  i.g.n.s.i.n.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.io.IOException: Invalid argument
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.grpc.netty.shaded.io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:807)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
19:26:23.217 [grpc-nio-worker-ELG-1-14] INFO  i.g.n.s.i.n.channel.nio.NioEventLoop - Migrated 0 channel(s) to the new Selector.
```

## Steps to Reproduce the Problem
Specific steps are unknown. The problem happens intermittently with different tests.

## Specifications

  - Version: 0.28.0 of service and Java SDK

**Comment by Spikhalskiy** [comment]
This problem wasn't noticed recently in any configuration of our unit test runs
