### ISSUE TITLE
`No PayloadConverter is registered for an encoding: binary/null`

### ISSUE THREAD

**Issue by jocho-here** [temporalio/sdk-java#1933]
## Expected Behavior
- `BinaryNullPayloadConverter` should be picked up to convert the payload that's `binary/null`

## Actual Behavior
- This is probably caused when we had a binary `null` in the payload, but rather threw an error without directly converting. I saw there is a `BinaryNullPayloadConverter` for Python SDK but not for Java SDK. Is this possibly a feature request?
- Our workflow threw `DataConverterException: No PayloadConverter is registered for an encoding: binary/null`
- the error:
```
Caused by: io.temporal.common.converter.DataConverterException: No PayloadConverter is registered for an encoding: binary/null
	at io.temporal.common.converter.PayloadAndFailureDataConverter.fromPayload(PayloadAndFailureDataConverter.java:89)
	at io.temporal.common.converter.PayloadAndFailureDataConverter.fromPayloads(PayloadAndFailureDataConverter.java:133)
	at io.temporal.internal.client.RootWorkflowClientInvoker.convertResultPayloads(RootWorkflowClientInvoker.java:500)
	at io.temporal.internal.client.RootWorkflowClientInvoker.getResult(RootWorkflowClientInvoker.java:220)
	at io.temporal.common.interceptors.WorkflowClientCallsInterceptorBase.getResult(WorkflowClientCallsInterceptorBase.java:51)
	at io.temporal.client.WorkflowStubImpl.getResult(WorkflowStubImpl.java:218)
```

## Specifications
  - Version: TemporalSDK: 1.22.0, Temporal-shaded:1.21.1
  - Platform: K8s

**Comment by Quinn-With-Two-Ns** [comment]
The [NullPayloadConverter](https://github.com/temporalio/sdk-java/blob/499593f4150b00c28f0694bc48837f36ab6e47a6/temporal-sdk/src/main/java/io/temporal/common/converter/NullPayloadConverter.java#L30C1-L30C1) and is part of the [default ](https://github.com/temporalio/sdk-java/blob/499593f4150b00c28f0694bc48837f36ab6e47a6/temporal-sdk/src/main/java/io/temporal/common/converter/DefaultDataConverter.java#L39C20-L39C20) data converter for Java does register itself for `binary/null`

**Comment by Quinn-With-Two-Ns** [comment]
If your not using the default data converter you need to  make sure `NullPayloadConverter` is registered.

**Comment by Quinn-With-Two-Ns** [comment]
Closing since Java does implement a `binary/null` data converter
