### ISSUE TITLE
Java SDK metrics don't work correctly with PrometheusRegistry

### ISSUE THREAD

**Issue by mastermanu** [temporalio/sdk-java#200]
## Expected Behavior
PrometheusMeterRegistry + MicrometerClientStatsReporter should successfully emit metrics to Prometheus.

## Actual Behavior
Metric Registration fails:
```
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'temporal_request_latency_seconds' containing tag keys [Operation]. The meter you are attempting to register has keys [Namespace, Operation, TaskQueue, WorkflowType].
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:419)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:403)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:197)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:308)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:612)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:566)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:306)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:539)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:433)
	at io.temporal.common.reporter.MicrometerClientStatsReporter.reportTimer(MicrometerClientStatsReporter.java:69)
	at com.uber.m3.tally.TimerImpl.record(TimerImpl.java:55)
	at com.uber.m3.tally.TimerImpl.recordStopwatch(TimerImpl.java:69)
	at com.uber.m3.tally.Stopwatch.stop(Stopwatch.java:48)
	at io.temporal.internal.grpc.GrpcMetricsInterceptor$MetricsClientCall$1.onClose(GrpcMetricsInterceptor.java:126)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:740)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondWorkflowTaskCompleted(WorkflowServiceGrpc.java:2673)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.lambda$sendReply$0(WorkflowWorker.java:369)
	at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109)
	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127)
	at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.sendReply(WorkflowWorker.java:362)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:313)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:275)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

## Steps to Reproduce the Problem

 ```
 PrometheusMeterRegistry registry = new PrometheusMeterRegistry(prometheusConfig);
 StatsReporter reporter = new MicrometerClientStatsReporter(registry);
      Scope scope =
          new RootScopeBuilder()
              .reporter(reporter)
              .reportEvery(com.uber.m3.util.Duration.ofSeconds(10));
      service =
          WorkflowServiceStubs.newInstance(
              WorkflowServiceStubsOptions.newBuilder()
                  .setTarget(target)
                  .setMetricsScope(scope)
                  .build());
```

## Specifications

  - Version: 0.29 SDK

**Comment by kkcmadhu** [comment]
thanks Manu, i was actually able to publish the metrics to another prometheus server which did not have any temporal related metrics reported already.
apart from the issue  that there is inconsistency in what tags are getting added by various components, i also see that the custom  tags are completely missing. more info here
https://community.temporal.io/t/attaching-custom-tags-workflow-metrics/526

**Comment by vitarb** [comment]
Prometheus requires each unique metric key to be always reported with the same set of tags.

Unfortunately our SDK is not very prometheus friendly and there are many code paths that may lead to partially filled tags for various operations, which results in errors during metric publishing like the one mentioned above.

While we don't have a proper fix yet, I can suggest a client work-around that may unblock you for now.
You could try adding default dummy values for common parameters in the root metric scope.

For example:
```
Scope scope = new RootScopeBuilder()
			.reporter(reporter)
			.tags(ImmutableMap.of(
					MetricsTag.NAMESPACE, "default",
					MetricsTag.ACTIVITY_TYPE, "none",
					MetricsTag.OPERATION_NAME, "none",
					MetricsTag.TASK_QUEUE, "none",
					MetricsTag.WORKFLOW_TYPE, "none"
			))
			.reportEvery(com.uber.m3.util.Duration.ofSeconds(10));
}
```

For example this should result in the following metrics being published for the above error case:
```
# TYPE temporal_request_latency_seconds_max gauge
temporal_request_latency_seconds_max{ActivityType="ExecuteRemoteTestStep",Namespace="java-bench",Operation="RespondActivityTaskCompleted",TaskQueue="temporal-bench",WorkflowType="config-driven-workflow",} 0.067643565
temporal_request_latency_seconds_max{ActivityType="RunDriver",Namespace="java-bench",Operation="RespondActivityTaskCompleted",TaskQueue="temporal-bench",WorkflowType="bench-driver",} 0.004640764
temporal_request_latency_seconds_max{ActivityType="None",Namespace="java-bench",Operation="ResetStickyTaskQueue",TaskQueue="None",WorkflowType="None",} 0.062871658
temporal_request_latency_seconds_max{ActivityType="None",Namespace="java-bench",Operation="StartWorkflowExecution",TaskQueue="temporal-bench",WorkflowType="config-driven-workflow",} 0.006228311
temporal_request_latency_seconds_max{ActivityType="None",Namespace="java-bench",Operation="RespondWorkflowTaskCompleted",TaskQueue="temporal-bench",WorkflowType="bench-driver",} 0.005130324
temporal_request_latency_seconds_max{ActivityType="RunDriver",Namespace="java-bench",Operation="RecordActivityTaskHeartbeat",TaskQueue="temporal-bench",WorkflowType="bench-driver",} 0.003844159
temporal_request_latency_seconds_max{ActivityType="RunMonitor",Namespace="java-bench",Operation="RecordActivityTaskHeartbeat",TaskQueue="temporal-bench",WorkflowType="bench-driver",} 0.003414754
temporal_request_latency_seconds_max{ActivityType="ExecuteRemoteTestStep",Namespace="java-bench",Operation="RecordActivityTaskHeartbeat",TaskQueue="temporal-bench",WorkflowType="config-driven-workflow",} 0.049534959
temporal_request_latency_seconds_max{ActivityType="None",Namespace="java-bench",Operation="RespondWorkflowTaskCompleted",TaskQueue="temporal-bench",WorkflowType="config-driven-workflow",} 0.073708412
temporal_request_latency_seconds_max{ActivityType="RunCleaner",Namespace="java-bench",Operation="RespondActivityTaskCompleted",TaskQueue="temporal-bench",WorkflowType="bench-driver",} 0.002968035
temporal_request_latency_seconds_max{ActivityType="RunMonitor",Namespace="java-bench",Operation="RespondActivityTaskCompleted",TaskQueue="temporal-bench",WorkflowType="bench-driver",} 0.003083715
temporal_request_latency_seconds_max{ActivityType="None",Namespace="java-bench",Operation="DescribeWorkflowExecution",TaskQueue="None",WorkflowType="None",} 0.010100332
temporal_request_latency_seconds_max{ActivityType="None",Namespace="java-bench",Operation="GetWorkflowExecutionHistory",TaskQueue="None",WorkflowType="None",} 0.011132755
```

Hope this helps you, meanwhile we are working on a proper solution on the SDK side.
