### ISSUE TITLE
NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 | Spring 3.3.1

### ISSUE THREAD

**Issue by Lavmee** [temporalio/sdk-java#2128]
## Expected Behavior
WorkflowServiceStubs Bean is created.

## Actual Behavior
Factory method 'workflowServiceStubs' threw exception with message: com/google/protobuf/GeneratedMessageV3
2024-06-26T12:51:09.185951139Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.10.jar!/:6.1.10]
2024-06-26T12:51:09.185951972Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.10.jar!/:6.1.10]
2024-06-26T12:51:09.185952764Z 	... 68 common frames omitted
2024-06-26T12:51:09.185953389Z Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3

## Steps to Reproduce the Problem

  1. Spring version 3.3.1 & Temporal version 1.24.0
  2. Create workflowServiceStubs Bean
```kotlin
    @Bean
    fun workflowServiceStubs(): WorkflowServiceStubs = WorkflowServiceStubs.newServiceStubs(
        WorkflowServiceStubsOptions {
            setTarget(temporalProperties.connectionTarget)
        }
    )
```

## Specifications

  - Version: 1.24.0

**Comment by Quinn-With-Two-Ns** [comment]
What version of protobuf are you using?

**Comment by Lavmee** [comment]
> What version of protobuf are you using?

I found the problem. I use Temporal SDK together with the [DGS](https://github.com/Netflix/dgs-framework) framework, which uses protobuf version 4.26.1

**Comment by Quinn-With-Two-Ns** [comment]
Yes protobuf `4.26` is know to be [problematic](https://github.com/grpc/grpc-java/issues/11015)

**Comment by Lavmee** [comment]
Now workaround for me: use shaded Temporal SDK, so I'm closing the issue. Thanks!
