### ISSUE TITLE
Flaky whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflows test

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#290]
The [failed build](https://buildkite.com/temporal/java-sdk/builds/706#8f286074-cb8e-488c-a0c8-6d952fc9800f).

The test output:
```
io.temporal.worker.StickyWorkerTest > whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflows[Docker] STANDARD_OUT
  | 19:28:41.314 [Test worker] INFO  io.temporal.internal.worker.Poller - start(): Poller{options=PollerOptions{maximumPollRateIntervalMilliseconds=1000, maximumPollRatePerSecond=0.0, pollBackoffCoefficient=2.0, pollBackoffInitialInterval=PT0.1S, pollBackoffMaximumInterval=PT1M, pollThreadCount=5, pollThreadNamePrefix='Host Local Workflow Poller'}, identity=014c4836-e433-491c-9982-b26ab8b220c4}
  |  
  | io.temporal.workflow.WorkflowTest > testUntypedChildStubWorkflowAsyncInvoke STANDARD_OUT
  | 19:28:41.342 [Time-limited test] INFO  io.temporal.internal.worker.Poller - start(): Poller{options=PollerOptions{maximumPollRateIntervalMilliseconds=1000, maximumPollRatePerSecond=0.0, pollBackoffCoefficient=2.0, pollBackoffInitialInterval=PT0.1S, pollBackoffMaximumInterval=PT1M, pollThreadCount=5, pollThreadNamePrefix='Host Local Workflow Poller'}, identity=0b8cce66-e6f6-45a6-9e5d-7581a6b8e38b}
  |  
  | io.temporal.worker.StickyWorkerTest > whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflows[Docker] STANDARD_OUT
  | 19:28:41.518 [Test worker] INFO  i.t.s.WorkflowServiceStubsImpl - shutdownNow
  |  
  | io.temporal.worker.StickyWorkerTest > whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflows[Docker] FAILED
  | java.lang.AssertionError: 1 expected:<2> but was:<1>
  | at org.junit.Assert.fail(Assert.java:89)
  | at org.junit.Assert.failNotEquals(Assert.java:835)
  | at org.junit.Assert.assertEquals(Assert.java:647)
  | at io.temporal.common.reporter.TestStatsReporter.assertCounter(TestStatsReporter.java:72)
  | at io.temporal.worker.StickyWorkerTest.whenStickyIsEnabledThenTheWorkflowIsCachedChildWorkflows(StickyWorkerTest.java:303)
```

**Comment by Spikhalskiy** [comment]
Not anymore
