### ISSUE TITLE
Query failure on terminated workflow

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#391]
## Expected Behavior
The query works for terminated workflows.

## Actual Behavior
```
Exception in thread "main" io.temporal.client.WorkflowQueryException: workflowId='7fc3ceac-eeb3-4468-983d-28716b21e858', runId='ea297429-0663-4c07-96db-e89cad466a09', workflowType='GreetingWorkflow'}
	at io.temporal.internal.sync.WorkflowStubImpl.query(WorkflowStubImpl.java:475)
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.queryWorkflow(WorkflowInvocationHandler.java:309)
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:272)
	at io.temporal.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:178)
	at com.sun.proxy.$Proxy4.queryGreeting(Unknown Source)
	at io.temporal.samples.hello.HelloQuery.main(HelloQuery.java:95)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: io.temporal.internal.replay.InternalWorkflowTaskException: Failure handling event 6 of 'EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED' type. IsReplaying=false, PreviousStartedEventId=3, workflowTaskStartedEventId=0, Currently Processing StartedEventId=3
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:193)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: io.temporal.internal.replay.InternalWorkflowTaskException: Failure handling event 6 of 'EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED' type. IsReplaying=false, PreviousStartedEventId=3, workflowTaskStartedEventId=0, Currently Processing StartedEventId=3

	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleEvent(ReplayWorkflowRunTaskHandler.java:140)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:180)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleQueryWorkflowTask(ReplayWorkflowRunTaskHandler.java:254)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleQueryOnlyWorkflowTask(ReplayWorkflowTaskHandler.java:257)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:112)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:314)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:280)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unexpected event:event_id: 6
```

## Steps to Reproduce the Problem
Terminate a workflow and run a query against it.

**Comment by bfugas** [comment]
I encountered the issue, reproduced it and posted a fix proposal.
I'm not sure if all the cases have been covered here. But I didn't want to make a big change to ignore all unknown events (go-sdk does it this way).

**Comment by Spikhalskiy** [comment]
`testShouldReturnQueryResultAfterWorkflowTimeout` added in #391 actually doesn't perform any workflow query in contrary to its name, so this issue shouldn't be closed. 
We don't know if the fix brought by #391 actually addresses the issue, this has to be rechecked.

**Comment by Spikhalskiy** [comment]
@vkoby Could you please improve `testShouldReturnQueryResultAfterWorkflowTimeout` to actually check the issue reported by Max and verify if it's fixed?

**Comment by Spikhalskiy** [comment]
This flake report actually shows that the issue wasn't fixed: https://github.com/temporalio/sdk-java/issues/630

**Comment by Spikhalskiy** [comment]
This issue is fixed. The flake https://github.com/temporalio/sdk-java/issues/630 has a different nature. The result depends on if workflow run times out before WFT heartbeat (local activity is used in that test) is received or after.
