### ISSUE TITLE
Activity retry not happening in cron workflow

### ISSUE THREAD

**Issue by arjunacharya10** [temporalio/sdk-java#401]
A Cron workflow which is triggered once every 30 days, if an activity throws error twice before returning the expected value. If we forward the testEnv to 90 days, then:

## Expected Behavior
The activity is called 3(number of times workflow is triggered in 90 days) * 3(number of times activity is called per workflow trigger) times = 9 times

## Actual Behavior
The activity is called 3 times, i.e not retried

## Steps to Reproduce the Problem

  1. In a test case, Start a workflow as a cron job, which runs once every 30 days
  2. Use a mock activity to throw IllegalStateException twice before returning the expected value
  3. Assert how many times the activity was called

## Specifications

  - Version: temporal-sdk:1.0.6, temporal-testing:1.0.6, temporal-testing-junit4:1.0.6
  - Platform:

**Comment by vitarb** [comment]
Hey Arjun, thanks for reporting this issue, I'm not sure if I understand your issue correctly, but I've tried to reproduce it, slightly modifying CronSample (see [here](https://github.com/vitarb/samples-java/commit/387d87f1817a6866e28554fb91939a0f6b699dad)) to throw exception 2 times in the activity before succeeding.
As expected I've seen 3 attempts for each workflow run:
```
Started workflow_id: "HelloCron"
run_id: "b378177e-cfa4-49d2-b975-b8367b8a68af"

21:58:00.441 [Activity Executor taskQueue="HelloCron", namespace="default": 1] WARN  i.t.i.sync.POJOActivityTaskHandler - Activity failure. ActivityId=cddb2eb7-c7b6-39b5-96d6-ab1edf74bb26, activityType=Greet, attempt=1
java.lang.IllegalStateException: Failing activity for HelloCron because execution attempt was 1
	at io.temporal.samples.hello.HelloCron$GreetingActivitiesImpl.greet(HelloCron.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:293)
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:252)
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:211)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21:58:01.458 [Activity Executor taskQueue="HelloCron", namespace="default": 2] WARN  i.t.i.sync.POJOActivityTaskHandler - Activity failure. ActivityId=cddb2eb7-c7b6-39b5-96d6-ab1edf74bb26, activityType=Greet, attempt=2
java.lang.IllegalStateException: Failing activity for HelloCron because execution attempt was 2
	at io.temporal.samples.hello.HelloCron$GreetingActivitiesImpl.greet(HelloCron.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:293)
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:252)
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:211)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192)
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
From HelloCron: Hello World!
```

It would help if you could provide a minimal sample that reproduces the issue you are talking about or a unit test.

**Comment by vitarb** [comment]
Resolving as there was no response.
