### ISSUE TITLE
Unable to replay a workflow after adding workflow versioning

### ISSUE THREAD

**Issue by srekapalli** [temporalio/sdk-java#482]
## Expected Behavior

After adding conditional logic based on the version , workflow replay should be able to process event history .

```
// Before
localActivityStub.process()

// After
int version = Workflow.getVersion("noLocalActivity", Workflow.DEFAULT_VERSION, 1)
if (version == Workflow.DEFAULT_VERSION) {
    // call Local activity
   localActivityStub.process()
} else {
    // directly set properties on the workflow result
}
```

## Actual Behavior

Receiving an error 

```
Caused by: java.lang.IllegalStateException: Unexpected local activity id: 7f5f265e-9487-3fa6-8bf1-37d3d70222ea
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleLocalActivityMarker(WorkflowStateMachines.java:369)
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleCommandEvent(WorkflowStateMachines.java:231)
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventImpl(WorkflowStateMachines.java:199)
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:178)
```

## Specifications

  - Version: 1.0.7 ( Java SDK)
  - Platform:

**Comment by vkoby** [comment]
@srekapalli, I attempted to reproduce this scenario but everything seems to behave correctly for me. Could you please look at the draft PR above and let me know if this test accurately describes your case?

**Comment by vkoby** [comment]
Going to close, but please feel free to reopen with a reproduction.
