### ISSUE TITLE
Activities advised with AspectJ are not recognised as implementation of @ActivityInterface anymore

### ISSUE THREAD

**Issue by adriil** [temporalio/sdk-java#586]
## Expected Behavior

From a working Spring Boot application that successfully registers Activities implementation with `io.temporal.worker.Worker.registerActivitiesImplementations`, when I add an `@Aspect` component to advise my Activities method, application should still start successfully.

## Actual Behavior

Application startup fails with the following log : `Class doesn't implement any non empty interface annotated with @ActivityInterface: com.example.test.InitialActivityImpl$$EnhancerBySpringCGLIB$$10ca071e`
```
{
	"@timestamp": "2021-07-12T18:54:43.736671+02:00",
	"application": "Test as a Service",
	"class": "org.springframework.beans.factory.support.ConstructorResolver",
	"correlation_id": "e6888554-0c11-485c-842b-7c010a0709bb",
	"data_version": 2,
	"description": "Application run failed",
	"environment": "dev",
	"exception_obj": {
		"cause": "Failed to instantiate [com.example.mos.configuration.SourceWorkerConfiguration$$EnhancerBySpringCGLIB$$bdd1899]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Class doesn't implement any non empty interface annotated with @ActivityInterface: com.example.test.InitialActivityImpl$$EnhancerBySpringCGLIB$$10ca071e",
		"message": "Error creating bean with name 'com.example.mos.configuration.SourceWorkerConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.mos.configuration.SourceWorkerConfiguration$$EnhancerBySpringCGLIB$$bdd1899]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Class doesn't implement any non empty interface annotated with @ActivityInterface: com.example.test.InitialActivityImpl$$EnhancerBySpringCGLIB$$10ca071e",
		"stacktrace": "org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.mos.configuration.SourceWorkerConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.mos.configuration.SourceWorkerConfiguration$$EnhancerBySpringCGLIB$$bdd1899]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Class doesn't implement any non empty interface annotated with @ActivityInterface: com.example.test.InitialActivityImpl$$EnhancerBySpringCGLIB$$10ca071e
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:313)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:294)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1203)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.example.app.Application.main(Application.java:44)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.mos.configuration.SourceWorkerConfiguration$$EnhancerBySpringCGLIB$$bdd1899]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Class doesn't implement any non empty interface annotated with @ActivityInterface: com.example.test.InitialActivityImpl$$EnhancerBySpringCGLIB$$10ca071e
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:309)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Class doesn't implement any non empty interface annotated with @ActivityInterface: com.example.test.InitialActivityImpl$$EnhancerBySpringCGLIB$$10ca071e
	at io.temporal.common.metadata.POJOActivityImplMetadata.<init>(POJOActivityImplMetadata.java:109)
	at io.temporal.common.metadata.POJOActivityImplMetadata.newInstance(POJOActivityImplMetadata.java:53)
	at io.temporal.internal.sync.POJOActivityTaskHandler.registerActivityImplementation(POJOActivityTaskHandler.java:110)
	at io.temporal.internal.sync.POJOActivityTaskHandler.registerActivityImplementations(POJOActivityTaskHandler.java:179)
	at io.temporal.internal.sync.SyncActivityWorker.registerActivityImplementations(SyncActivityWorker.java:55)
	at io.temporal.worker.Worker.registerActivitiesImplementations(Worker.java:326)
	at com.example.mos.configuration.SourceWorkerConfiguration.<init>(SourceWorkerConfiguration.java:93)
	at com.example.mos.configuration.SourceWorkerConfiguration$$EnhancerBySpringCGLIB$$bdd1899.<init>(<generated>)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
	... 21 more
",
		"type": "org.springframework.beans.factory.BeanCreationException"
	},
	"level": "ERROR",
	"line": 313,
	"method": "instantiate",
	"number_of_events": 1,
	"request_id": "e6888554-0c11-485c-842b-7c010a0709bb",
	"roletype": "dev",
	"thread": "main",
	"type": "log"
}
```

## Steps to Reproduce the Problem

  1. Considering an application that registers the following Activity implementation
  ```java
  @ActivityInterface(namePrefix = "myactivity")
  public interface MyActivity {
      void run(Object param);
      void rollback(Object param);
  }

  @Slf4j
  @Component
  public class MyActivityImpl implements MyActivity {

      @Override
      public void run(Object param) {
          log.info("Initiate Activity - Running the default run method");
      }

      @Override
      public void rollback(Object param) {
        log.info("Initiate Activity - Running the default rollback method");
      }
  }
  ```
  2. The implementation is registered like the following
  ```java
  worker.registerActivitiesImplementations(myActivityImpl);
  ```
  3. Add an `@Aspect` component to advise your Activity implementation methods
  ```java
@Slf4j
@Aspect
@Component
public class MyLoggerAspect {

    /**
     * Matches activities run/rollback methods.
     *
     * @param method Activity's run/rollback method
     * @throws Throwable any exception Activity method might throw
     */
    @Around("execution(* com.example.test.*.*(java.lang.Object))")
    public void aroundActivityMethod(ProceedingJoinPoint method) throws Throwable {
        log.info("Starting the Activity");

        // Run the activity method
        method.proceed();
       
        log.info("Activity completed")
    }
  ```
  4. Start the application -> it fails
  5. Comment the line with the `@Around` or put a different path that doesn't match the Activity implementation path and try again -> application startup successful

## Specifications

  - Version: 
    - SDK `1.0.4`,  `1.0.7` and `1.1.0`
    - Sprint Boot `2.1.9`
  - Platform: macOS Big Sur, OpenJDK 11

**Comment by adriil** [comment]
After some research I've found out that this is because of Spring AOP proxying the advised classes using CGLIB by default.

Because of this, the advised Activity implementation that `worker` receives is actually a proxy to the implementation but not the implementation itself (debug view below).
```
1 = {InitialActivityImpl$$EnhancerBySpringCGLIB$$cbcf576b@14778} "com.[...].InitialActivityImpl@3ea9b180"
 CGLIB$BOUND = false
 CGLIB$CALLBACK_0 = {CglibAopProxy$DynamicAdvisedInterceptor@14792} 
 CGLIB$CALLBACK_1 = {CglibAopProxy$StaticUnadvisedInterceptor@14793} 
 CGLIB$CALLBACK_2 = {CglibAopProxy$SerializableNoOp@14794} 
 CGLIB$CALLBACK_3 = {CglibAopProxy$StaticDispatcher@14795} 
 CGLIB$CALLBACK_4 = {CglibAopProxy$AdvisedDispatcher@14796} 
 CGLIB$CALLBACK_5 = {CglibAopProxy$EqualsInterceptor@14797} 
 CGLIB$CALLBACK_6 = {CglibAopProxy$HashCodeInterceptor@14798} 
 migrationService = null
```

So I needed to add the non-empty `@ActivityInterface` interface inside of the proxy, which could be achieved with the code below : 
* a custom `AnnotationAwareAspectJAutoProxyCreator` that adds the interface to the ProxyFactory
```java
public class CompanyMigrationAspectProxyCreator extends AnnotationAwareAspectJAutoProxyCreator {

    /**
     * Map that gives the correct non-empty @ActivityInterface for each Activities.
     */
    private final Map<Class, Class> activityImplAndInterface;

    @Autowired
    public CompanyMigrationAspectProxyCreator(final InitiateActivity initiateActivityImpl) {
        activityImplAndInterface = Map.of(initiateActivityImpl.getClass(), InitiateActivity.class);
    }

    /**
     * Customizes AOP proxies of our Activities to add non-empty @ActivityInterface required by Temporal SDK.
     *
     * @param proxyFactory the proxy factory
     */
    @Override
    protected void customizeProxyFactory(ProxyFactory proxyFactory) {
        Class<?> activityInterface = activityImplAndInterface.get(proxyFactory.getTargetClass());

        if (activityInterface != null) {
            proxyFactory.addInterface(activityInterface);
        }
    }

}
```
* a little hack taken from [there](https://github.com/spring-projects/spring-boot/issues/25367#issuecomment-781999430) that allows to inject my custom AnnotationAwareAspectJAutoProxyCreator instead of the regular one, when applicable
```java
    /**
     * Injects our own AnnotationAwareAspectJAutoProxyCreator ({@link CompanyMigrationAspectProxyCreator})
     * to answer Temporal requirements to have Activities proxies to proxy non-empty @ActivityInterface.
     *
     * @return bean factory post processor
     */
    @Bean
    static BeanFactoryPostProcessor replaceDefaultAspectAutoProxyCreator() {
        return (beanFactory) -> {
            BeanDefinition definition = beanFactory.getBeanDefinition(AopConfigUtils.AUTO_PROXY_CREATOR_BEAN_NAME);
            if (AnnotationAwareAspectJAutoProxyCreator.class.getName().equals(definition.getBeanClassName())) {
                definition.setBeanClassName(CompanyMigrationAspectProxyCreator.class.getName());
            }
        };
    }
```
