### ISSUE TITLE
Support Spring Proxy classes marked with @Component for activities

### ISSUE THREAD

**Issue by ginachen-netflix** [temporalio/sdk-java#718]
**Is your feature request related to a problem? Please describe.**
Right now when i try to registerActivitiesImplementations with a Spring Proxy bean, it failed with error 

```
Caused by: java.lang.IllegalArgumentException: Class doesn't implement any non empty interface annotated with @ActivityInterface: 
xxx.xxx.xxx.ActivityImpl$$EnhancerBySpringCGLIB$$40723738
	at io.temporal.common.metadata.POJOActivityImplMetadata.<init>(POJOActivityImplMetadata.java:109) ~[temporal-sdk-0.11.0+1-0-7.jar:0.11.0+1-0-7]
	at io.temporal.common.metadata.POJOActivityImplMetadata.newInstance(POJOActivityImplMetadata.java:53) ~[temporal-sdk-0.11.0+1-0-7.jar:0.11.0+1-0-7]
	at io.temporal.internal.sync.POJOActivityTaskHandler.registerActivityImplementation(POJOActivityTaskHandler.java:110) ~[temporal-sdk-0.11.0+1-0-7.jar:0.11.0+1-0-7]
	at io.temporal.internal.sync.POJOActivityTaskHandler.registerActivityImplementations(POJOActivityTaskHandler.java:179) ~[temporal-sdk-0.11.0+1-0-7.jar:0.11.0+1-0-7]
	at io.temporal.internal.sync.SyncActivityWorker.registerActivityImplementations(SyncActivityWorker.java:55) ~[temporal-sdk-0.11.0+1-0-7.jar:0.11.0+1-0-7]
	at io.temporal.worker.Worker.registerActivitiesImplementations(Worker.java:326) ~[temporal-sdk-0.11.0+1-0-7.jar:0.11.0+1-0-7]
```

Looking through the code, the `ActivityInterface` was not recognized as an interface in Proxy class.

**Describe the solution you'd like**
We want to make this activity class recognizable.

**Describe alternatives you've considered**
N/A.

**Additional context**
How to attach a screenshot? lol

**Comment by Spikhalskiy** [comment]
Hi Gina,

Any chance you can provide an example of your wiring or at least how do you specifically make the injection?
If you inject (or request from the Spring container) specific Activity interfaces - Spring proxies should implement the right interfaces.

My guess is that your wiring is probably organized in a way that all activities are implementing some marker interface and you ask Spring to give a collection of all instances implementing this marker interface. This will not work because Spring will create proxies that implement the marker interface only, but not actual Activity interfaces.

Let me know if you can share more information here.
