### ISSUE TITLE
TestEnvironmentOptions.Builder.validateAndBuildWithDefaults fails

### ISSUE THREAD

**Issue by smax48** [temporalio/sdk-java#749]
## Expected Behavior
It was working fine in SDK v1.1

## Actual Behavior
When upgraded to v1.3.1, I get this error:

```
Only one of the target and channel options can be set at a time
java.lang.IllegalStateException: Only one of the target and channel options can be set at a time
	at io.temporal.serviceclient.WorkflowServiceStubsOptions.<init>(WorkflowServiceStubsOptions.java:179)
	at io.temporal.serviceclient.WorkflowServiceStubsOptions.<init>(WorkflowServiceStubsOptions.java:34)
	at io.temporal.serviceclient.WorkflowServiceStubsOptions$Builder.validateAndBuildWithDefaults(WorkflowServiceStubsOptions.java:657)
	at io.temporal.serviceclient.WorkflowServiceStubsImpl.<init>(WorkflowServiceStubsImpl.java:111)
	at io.temporal.serviceclient.WorkflowServiceStubs.newInstance(WorkflowServiceStubs.java:51)
	at io.temporal.testing.TestWorkflowEnvironmentInternal.<init>(TestWorkflowEnvironmentInternal.java:80)
	at io.temporal.testing.TestWorkflowEnvironment.newInstance(TestWorkflowEnvironment.java:99)
```

## Steps to Reproduce the Problem

This code crashes:

```
    private val testEnv: TestWorkflowEnvironment = TestWorkflowEnvironment.newInstance(
        TestEnvironmentOptions.newBuilder()
            .setWorkflowClientOptions(
                WorkflowClientOptions.newBuilder()
                    .validateAndBuildWithDefaults()
            ).setWorkerFactoryOptions(
                WorkerFactoryOptions.newBuilder()
                    .validateAndBuildWithDefaults()
            ).validateAndBuildWithDefaults()
    )
```

PS 
When I use just build() - it works OK

## Specifications

  - Version: Java SDK 1.3.1

**Comment by vitarb** [comment]
Looks like the problem is that when you call validateAndBuildWithDefaults on TestEnvironmentOptions builder it creates default service options with default target address, which then gets passed to the WorkflowServiceStubsImpl that also adds a channel for the in-memory service, which causes the error you are seeing (both target and channel set). The fix is rather simple, we should remove target when we are populating the channel. PR linked above should fix the issue.

**Comment by smax48** [comment]
yeah, I debugged this a bit and was thinking something similar. Just strange that I was first to pick this up :)
Thanks for quick response!
