### ISSUE TITLE
DescribeTest#testSuccessfulActivity fails with Docker

### ISSUE THREAD

**Issue by vkoby** [temporalio/sdk-java#790]
at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at io.temporal.workflow.DescribeTest.testSuccessfulActivity(DescribeTest.java:165)

**Comment by Spikhalskiy** [comment]
It's most likely a result of merging https://github.com/temporalio/temporal/pull/2007
So, changes in the Test Service and `testSuccessfulActivity` test for https://github.com/temporalio/sdk-java/issues/766 should be implemented to make it fixed.

**Comment by Spikhalskiy** [comment]
Closed by #782
